### ISSUE TITLE
Logging.log_internal's Output 

### ISSUE THREAD

**Issue by sshaw** [TwP/logging#104]
I'd like to use this call (some more) [in my custom logger](https://github.com/sshaw/logging-appenders-airbrake) to see what Airbrake is up to when an error is logged. Of course Airbrake's log shouldn't go to the configured loggers.  

Can `Logging.log_internal` be used for this? I tried sometime ago and, if I recall correctly, it's a noop.

**Comment by TwP** [comment]
You can use `Logging.log_internal` if you like. However that appender is disabled by default. If you fire up an IRB session and load the [`examples/hierarchies.rb`](https://github.com/TwP/logging/blob/master/examples/hierarchies.rb) you will see the following output:

```
irb(main):001:0> load 'examples/hierarchies.rb'
 WARN  Foo : this is a warning, not a ticket
ERROR  Foo::Bar : but this error message will be logged
 WARN  Foo::Baz : this message will be logged twice - once by Foo and once by root
 WARN  Foo::Baz : this message will be logged twice - once by Foo and once by root
 WARN  Foo::Bar : foo is no longer passing log events up to it's parent
============================================================================
root  ............................................  *debug      -T
- <Appenders::Stdout:0x3ff05c8a1ad8 name="stdout">
  Foo  ...........................................   *warn  -A  -T
  - <Appenders::Stdout:0x3ff05c8a1ad8 name="stdout">
    Foo::Bar  ....................................    warn  +A  -T
    Foo::Baz  ....................................    warn  +A  -T
  Logging  .......................................    *off  -A  -T
```

Everything below the `=========` line is the current configuration of the Logging framework. The last line there indicates that the logger being used by the Logging framework is turned off and it is not additive - i.e. log events will not be propagated up the logging hierarchy to the root logger and the `Stdout` appender attached to the root logger.

To get output from the internal logging framework, you will need to set a log level and either attach an appender (if you want to send internal log messages to a file) or make the logger additive so it can propagate events to the root logger which usually has an appender.

```ruby
logger = Logging.logger['Logging']
logger.level = :info

# propagate events up the hierarchy
logger.additive = true

# or you can add an appender
logger.appenders = Logging.appenders.stderr
```

I hope that gets you going in the right direction. Please throw more questions in here and I'll try and answer them.

**Comment by sshaw** [comment]
So it's is just another logger that can be configured (makes sense, of course) and a lib should not impose a specific config for it on users. If the user wan't to see `log_internal` let them modify their config. Thanks for the info, though it seems that `Logging.log_internal` should accept a symbolic level and not just a `Fixnum`:

```
irb [2.2.0] (logging)$ Logging.logger['Logging'].level = :info
=> :info
irb [2.2.0] (logging)$ Logging.logger.root.appenders = Logging.appenders.stderr
=> <Appenders::Stderr:0x3fe1e180ff54 name="stderr">
irb [2.2.0] (logging)$ Logging.logger['Logging'].additive = true
=> true
irb [2.2.0] (logging)$ Logging.log_internal { "Log..." }
 INFO  Logging : Log...
irb [2.2.0] (logging)$ Logging.log_internal(4) { "Log..." }
FATAL  Logging : Log...
=> true
irb [2.2.0] (logging)$ Logging.log_internal(:fatal) { "Log..." }
TypeError: no implicit conversion of Symbol into Integer
	from /Users/sshaw/code/ruby/logging/lib/logging.rb:497:in `[]'
	from /Users/sshaw/code/ruby/logging/lib/logging.rb:497:in `log_internal'
	from (irb):21
	from /Users/sshaw/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
```

**Comment by TwP** [comment]
It only accepts a numeric value because we do not know what symbolic level the user has configured. The standard symbolic levels of `:debug`, `:info`, `:warn`, `:error`, `:fatal` can be changed at runtime. So we cannot rely on their existence.
