### ISSUE TITLE
Redefining Thread#new breaks subclassing of Thread by other gems / code

### ISSUE THREAD

**Issue by paulspringett** [TwP/logging#106]
Maybe I haven't fully understood what the [code here](https://github.com/TwP/logging/blob/logging-1.8.0/lib/logging/diagnostic_context.rb#L281-L328) does but it appears to break subclassing of Thread by changing the arguments sent to `Thread#new`.

Take for example the gem [serverengine](https://github.com/fluent/serverengine) which subclasses `Thread` and [implements it's own `initialize` method](https://github.com/fluent/serverengine/blob/master/lib/serverengine/signal_thread.rb#L21). Without requiring the logging gem, calling `ServerThread.new {}` works but when requiring logging, you get:

```
$ irb
irb(main):001:0> require 'logging'
=> true
irb(main):002:0> require 'serverengine'
=> true
irb(main):003:0> ServerEngine::SignalThread.new {}
ArgumentError: wrong number of arguments (2 for 0)
  from vendor/bundle/ruby/2.0.0/gems/serverengine-1.5.10/lib/serverengine/signal_thread.rb:21:in `initialize'
  from vendor/bundle/ruby/2.0.0/gems/logging-1.8.0/lib/logging/diagnostic_context.rb:320:in `new'
  from vendor/bundle/ruby/2.0.0/gems/logging-1.8.0/lib/logging/diagnostic_context.rb:320:in `create_with_logging_context'
  from vendor/bundle/ruby/2.0.0/gems/logging-1.8.0/lib/logging/diagnostic_context.rb:288:in `new'
  from (irb):3
  from /opt/songkick/ruby20/bin/irb:12:in `<main>'
``` 

I believe this is happening because in the `create_with_logging_context` method you're changing the arguments sent to `#new` which in turn get passed to `#initialize` (in `Thread` itself and subclasses).

It seems very reasonable that the serverengine gem should be able to depend on the Ruby core implementation of `Thread` with it being changed by other gems.

I've hacked together a workaround but I think this is a bug that should be addressed by the logging gem.

Work around looks a bit like this:

```
module ServerEngine
  class SignalThread
    def self.new(*args)
      _orig_new(*args)
    end
  end

  class ProcessManager
    class HeartbeatThread
      def self.new(*args)
        _orig_new(*args)
      end
    end
  end
end
```

**Comment by TwP** [comment]
This has been fixed. Upgrade to logging-1.8.2 and everything will work as expected.

And thank you for the backtrace and the good explanation of what was going on. These types of issue reports make it so much easier to figure out what is going on.

**Comment by paulspringett** [comment]
@TwP thank you for fixing this, really appreciate it :) :+1:
