### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by dsandber** [TwP/logging#107]
I'm using logging (1.8.2) and logging-rails (0.4.0) in my rails app.  I found the following while hunting a memory leak:

Leaked 8 DATA objects of size 0/3150896 at: .../.rvm/gems/ruby-2.1.5/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:320

It appears that 3 megabytes was leaked in a pretty short amount of time.

diagnostic_context.rb warns "... If any of those references end up in the binding, then they cannot be garbage collected until the child thread exits."

So it appears that memory is leaking because of diagnostic_context.  But I'm not sure what I did to cause this or how to fix it.  Can the diagnostic context be turned off?

Thanks!

**Comment by dsandber** [comment]
I'm using unicorn which forks the process to make multiple workers.  Thought I'd mention that since I know fork can interact strangely with threads.

**Comment by swistaczek** [comment]
Hey, I found the same issue while using celluloid with logging.

**Comment by TwP** [comment]
Thanks for reporting this memory leak. Would you be wiling to try out an experiment? Immediately after forking, please call:

```ruby
Logging.clear_diagnostic_contexts
Logging.reopen
```

The call to `clear_diagnostic_contexts` will remove all the ruby objects used to store diagnostic information. The call to `reopen` walks over all the appenders and reopens any IO file descriptors.

Please let me know if that helps. I'll continue hunting on my end.

**Comment by TwP** [comment]
And a question for clarification. Is the memory leak happening in the parent process or in the child process?

The calls I mentioned above should occur in the **child** process immediately after forking. I'm assuming that is where the memory leak is occurring.

Also, could you run this snippet of code in a process showing the leak:

```ruby
require 'pp'

Thread.exclusive do
  Thread.list.each do |thread|
    STDOUT.puts "## Thread: #{thread.object_id}"

    STDOUT.puts "-- MDC Name --"
    pp thread[Logging::MappedDiagnosticContext::NAME]

    STDOUT.puts "-- MDC Stack Name --"
    pp thread[Logging::MappedDiagnosticContext::STACK_NAME]

    STDOUT.puts "-- NDC Name --"
    pp thread[Logging::NestedDiagnosticContext::NAME]

    STDOUT.puts "## Done ##"
  end
end
```

I'm curious how many threads are running and how large the diagnostic contexts are.

**Comment by TwP** [comment]
I've been digging into this a little more tonight. I created a gist - https://gist.github.com/TwP/34bbab82c93d87971352 - to try and get some memory leaks. But alas, I cannot get Logging alone to leak objects.

In that script, each forked child process will spin up **lots** of threads and log messages. Information about the diagnostic contexts are written to a file, and the current counts from the `ObjectSpace` are also written to the file.

The first information dump:

```
## [10365] main - run
## MDC: nil
## MDC Stack: [{"pid"=>10365, "first"=>"John", "last"=>"Doe"}]
## NDC: nil
## --------
#### [10365] Found 1 threads
{:TOTAL=>33013, :FREE=>15235, :T_OBJECT=>188, :T_CLASS=>1094, :T_MODULE=>85, :T_FLOAT=>6, :T_STRING=>9905, :T_REGEXP=>182, :T_ARRAY=>1756, :T_HASH=>84, :T_STRUCT=>6, :T_BIGNUM=>1, :T_FILE=>4, :T_DATA=>2573, :T_COMPLEX=>1, :T_RATIONAL=>1, :T_NODE=>1777, :T_ICLASS=>115}
################################################################################
```

And the very last information dump:

```
## [10365] main - run
## MDC: {"pid"=>10365, "first"=>"John", "last"=>"Doe"}
## MDC Stack: [{"pid"=>10365, "first"=>"John", "last"=>"Doe"}]
## NDC: nil
## --------
#### [10365] Found 1 threads
{:TOTAL=>33013, :FREE=>15232, :T_OBJECT=>188, :T_CLASS=>1094, :T_MODULE=>85, :T_FLOAT=>6, :T_STRING=>9905, :T_REGEXP=>182, :T_ARRAY=>1756, :T_HASH=>84, :T_STRUCT=>6, :T_BIGNUM=>2, :T_FILE=>4, :T_DATA=>2575, :T_COMPLEX=>1, :T_RATIONAL=>1, :T_NODE=>1777, :T_ICLASS=>115}
################################################################################
```

The count for Array and Hash objects are the same. The only object types that have increased are `T_BIGNUM` (by 1) and `T_DATA` (by 2).

So taken by itself, the Logging framework is not holding onto references or leaking objects.

**Comment by TwP** [comment]
@dsandber / @swistaczek could either of you provide me with an example ruby script that demonstrates this memory leak?

**Comment by TwP** [comment]
If you look at [line 320 in `diagnostic_context.rb`](https://github.com/TwP/logging/blob/logging-1.8.2/lib/logging/diagnostic_context.rb#L320) you'll see that this is calling the actual `Thread#new` method. All the objects you are seeing as "leaked" are threads.

Each thread has an associated `Binding` - the execution context for the running state of the thread. This will contain lots of data for larger applications. So your applications are holding onto threads.

In Celluloid, an internal thread pool is maintained to reuse threads. So having long running threads hanging around is the norm in Celluloid.

Again, use `ObjectSpace.each_object(Thread)` to confirm that you have the appropriate number of threads in your application. If you see more threads than you expect, then something in your application is holding onto thread references. You'll have to hunt that down and fix it.

**Comment by blewa** [comment]
Here's the issue in my use case:
I've got an app that consumes messages off of an external queue, then dispatches those messages out to workers for processing and passage out to a daemon via TCP.  There are at least 4 threads at play at any given time:

1. The main thread
1. The thread that connects to the external queue and waits for messages
1. At least one worker thread
1. The thread that takes messages from the worker threads (from an internal ruby Queue object) and pushes them out via TCP.

The app processes hundreds of messages per second and runs as a daemon, so all threads should live for days if not weeks or months.  At this point I'm working around the issue by calling out to Logging.clear_diagnostic_contexts and Logging.reopen at regular intervals, but that seems sort of hackish.  Is logging just not meant to be used with long running threads at this time or am I missing something on my side?

Thanks!

**Comment by TwP** [comment]
@blewa open a new issue if you are having problems with Logging. All this issue is saying is that Logging is **not** leaking objects. Everything is getting GC'd correctly from all the tests that I ran locally.
