### ISSUE TITLE
any plans to release 2.0.0 ?

### ISSUE THREAD

**Issue by gingerlime** [TwP/logging#108]
I'd love to use the filter capabilities in master. Are there any concrete plans to release it? 

... and hopefully `logging-rails` will be happy with the latest version. For some reason, I couldn't get bundler to use the latest `logging` from github with `logging-rails`...

**Comment by TwP** [comment]
Oh there are plans. Unfortunately life and work keep interfering with getting this out the door.

The last thing I want to do for a 2.0 release is to move the email appender into its own ruby gem. People have asked for examples of writing their own appenders, and I would like the email appender to be the canonical example for doing just that.

**Comment by gingerlime** [comment]
Any chance to release `1.9` meanwhile then with filters? :)

Also (I can open an issue / PR on `logging-rails` for this, but it's related), does it make sense to remove or relax the [version restriction](https://github.com/TwP/logging-rails/blob/master/Rakefile#L18) on `logging-rails`, so it can be used with the master version of `logging` until it's properly released?

As for extracting the appender Gem. I'd be happy to volunteer for helping of this, assuming it's mostly the technical aspects of extracting it. I'm guessing it involves more than that though...?

**Comment by TwP** [comment]
Logging 2.0.0 has been released.

**Comment by gingerlime** [comment]
Thanks @TwP! Very happy to hear.

I <3 logging - it does a great job at handling logging and the adapter / filter system makes it very flexible. 

I saw that `logging-rails` was also updated, but the rubygem version is still the old one (or maybe it's cached?). Hope it's also going to get updated, so everything's in sync.
