### ISSUE TITLE
No silence method in Logger

### ISSUE THREAD

**Issue by dwo** [TwP/logging#11]
Hi! I was recently using another gem with our rails app which made some assumptions about the Rails logger, specifically that it had the "silence" method. We use your logging gem as the logger in our Rails app as well as in some other smaller non-rails projects around our website's architecture. Essentially, I ran into problems when this gem started trying to pass blocks to "silence" on our logger.

Is there any reason you haven't included a method similar facility to what Rails provides to temporarily adjust the logging level for a block? The code is quite simple and seems like a sensible pattern for a logger, would you be interested in having it ported over to your gem? -> http://apidock.com/rails/Logger/silence

**Comment by n-rodriguez** [comment]
However you can still do with some monkey patching (if you really need it) :

```ruby
module LoggingPatch
  module RailsCompat
    def silence( *args )
      old_level  = self.level
      self.level = :error

      yield
    ensure
      self.level = old_level
    end
  end
end
Logging::RailsCompat.prepend(LoggingPatch::RailsCompat)
```
