### ISSUE TITLE
Migrating from 1.8.2 to 2.0.0

### ISSUE THREAD

**Issue by ant31** [TwP/logging#112]
Hi, 

Do you have any documentation to to migrate from 1.8 to 2.x? 

In fact I have an error:
```ruby
NoMethodError: undefined method `trace=' for <Logging::RootLogger:0x3f9c53e6d7bc name="root">:Logging::RootLogger
```

Digging the code it looks like the method has been renamed ```caller_tracing```.

I'm looking for compatibility issues/actions list? 

Thx

**Comment by TwP** [comment]
Take a look at [`History.txt`](https://github.com/TwP/logging/blob/master/History.txt) for the latest changes. Another good place to look is the git changes themselves:

```shell
git log --pretty=oneline --abbrev-commit --graph --decorate
```

That will produce a pretty output of what has changed in 2.0.0
