### ISSUE TITLE
How to create default layout pattern to refer :layout?

### ISSUE THREAD

**Issue by piya23300** [TwP/logging#113]
it like `:color_scheme`

```
Logging.color_scheme( :bright,
          :levels => {
            :info  => :green,
            :warn  => :yellow,
            :error => :red,
            :fatal => [:white, :on_red]
          },
          :date => :blue,
          :logger => :cyan,
          :message => :magenta
        )
Logging.layouts.pattern(
            :pattern => '[%d] %-5l: %m\n',
            :date_pattern  =>  "%Y-%m-%d %H:%M:%S",
            :date_method   =>  'to_s',
            :color_scheme  =>  :bright
          )
```

I use `:bright` for reference

so `:layout`
I would like to use `:pattern_name` for reference

```
default_layout = Logging.layouts.pattern(
            :pattern => '[%d] %-5l: %m\n',
            :date_pattern  =>  "%Y-%m-%d %H:%M:%S",
            :date_method   =>  'to_s',
            :color_scheme  =>  :bright
          )

Logging.appenders.file( 'Onebox Core Gem Log',
          :filename => 'log/onebox_core.log',
          :layout => default_layout
        )
```

How to create default layout pattern to refer :layout?

**Comment by TwP** [comment]
Color schemes can be assigned short names like `:bright`. But Layouts do not have short names. The method you showed in your comment is the correct way to create a pattern for later use:

```ruby
default_layout = Logging.layouts.pattern( ... )
```

**Comment by olleolleolle** [comment]
This question has now been answered.

Is this a common enough question that the documentation needs changing, or can this issue be closed now?

**Comment by piya23300** [comment]
The answer is the gem can not create short names of a layout.

Thank you.

**Comment by TwP** [comment]
I've added an example showing how to reuse layouts. You brought up a good point, @olleolleolle, that since the question had been asked more than once it most likely means it needs clarification.
