### ISSUE TITLE
[PROPOSAL] use block forms as conditional evaluation (not for logging)

### ISSUE THREAD

**Issue by doudou** [TwP/logging#118]
Logging inherited Ruby's logger behaviour that the block form is meant to return the message to be logged. I've been for years using the blocks to instead have conditional evaluation, in cases where I need to build big log messages, e.g.

~~~
logger.debug do
   debug "a message"
   array.each do |element|
      debug "  #{element}"
   end
   break
end
~~~

The trick obviously being to not forget the 'break' at the end. I was wondering if you would have an idea on how to "mainline" this use case without requiring the break ....

**Comment by TwP** [comment]
I don't think your code will work as shown with the logging gem. The bare `debug` method will be executed against the `Object` class which does not have that method defined. The closest you could get would be ...

```ruby
if logger.debug?
  logger.debug "message"
  array.each { |element| logger.debug element.to_s }
end
```

**Comment by doudou** [comment]
The bug in the proposed code is fairly irrelevant to the underlying proposal. I'd like to have a way to format a multi-line message properly ... and ideally keeping with the ```log_level do ... end``` for clarity.

**Comment by TwP** [comment]
The only way to achieve what you want is to change the behavior of the block form. It would have to ignore the returned value, but that is definitely not the expected behavior. So including `break` at the end of the block really seems like the best way to go. Sorry  ¯\\\_(ツ)\_/¯

**Comment by doudou** [comment]
OK ... Just wanted to see if someone would have a good idea to integrate this kind of functionality.
