### ISSUE TITLE
Formatting of timestamps

### ISSUE THREAD

**Issue by tilo** [TwP/logging#122]
Is there a way to format timestamps differently? e.g. to print them as UTC, or as UNIXtime?

In the code #iso8601_format seems to be hard-coded. 

It would be good if the time-formatting was customizable.

**Comment by TwP** [comment]
You want to use a `Pattern` layout and specify the `:date_pattern` when the layout is created. See the initializer docs here: https://github.com/TwP/logging/blob/master/lib/logging/layouts/pattern.rb#L202-L220

```ruby
layout = Logging.layouts.pattern(:date_pattern => "%Y-%m-%d %H:%M:%S")
Logging.appenders.stdout(:level => :info, :layout => layout)
```
