### ISSUE TITLE
Way to disable monkey patching of Thread methods?

### ISSUE THREAD

**Issue by ivoanjo** [TwP/logging#155]
Hello! Thanks for the awesome logging gem :smile: 

I'm working on a system where we create threads through pools, and always reuse them, so in this case the inheritance of diagonostic contexts is not really useful at all (and rather confusing when looking at thread traces).

With this use case, I would like to ask for the ability to disable the monkey patches that `logging` does to `Thread`. It's not an essential use case (e.g. we can and we do live with it), but it would be awesome to have one less monkey patch needed to the core library.

**Comment by TwP** [comment]
Hello @ivoanjo! Thank you for the suggestion. Would you be willing to help brainstorm (and possibly implement :grin:) a way to make the `Thread` creation overloading optional?

The `Thread` creation methods are overridden when Logging is first loaded. One solution is to set and environment variable that controls this override logic. You would need to set this environment variable before requiring the Logging framework.

```ruby
ENV["LOGGING_OVERRIDE_THREAD_NEW"] = false

require 'logging'
```

One benefit of using the environment variable is that you can now safely rely on `Bundler.setup` to configure your gem dependencies. You would have to set the environment variable in the shell before starting your application.

Thoughts on this approach :thought_balloon:? Is there another, easier way to accomplish this?

**Comment by ivoanjo** [comment]
Thanks for the reply! I am definitely available to help out on this one :)

Indeed thinking about it, I see only two options:
* Doing it via an env flag, as you suggested
* Doing it via a different require. E.g. split the thread monkey patching into a separate file, and by default when you did `require 'logging'` that file would be loaded, but if you did `require 'logging-core'` or `require 'logging/core'` the monkey patching would not be applied.

You could even combine both: maybe `logging-core.rb` (or some better name) just sets the env var and requires `logging` anyway.

I think either approach works and doesn't have a lot of downsides --- it's easy enough to set an env var or change your requires (in your app or on the `Gemfile` directly).
