### ISSUE TITLE
How to turn off colored output?

### ISSUE THREAD

**Issue by ghostsquad** [TwP/logging#175]
How does one turn off colored output? I don't see it in the documentation. It seems if you are using the console logger, and don't specify a color scheme, it sets a default one. Thanks!

**Comment by ufo2mstar** [comment]
Hey @ghostsquad ,
By default, logging does not apply colors to your log message texts.
When initializing your layout for your appender, either:
1. omit your `color_scheme` parameter or 
2. just set `color_scheme: nil,`.. 
and this should prevent the [log message colorization](https://github.com/TwP/logging/blob/master/examples/colorization.rb)

Cheers!
