### ISSUE TITLE
how generate a file with all the outputs?

### ISSUE THREAD

**Issue by jpaitken** [TwP/logging#176]
Hi i am new and i need generate a file.log with all the outputs that the logger provides, someone could help me?

**Comment by ufo2mstar** [comment]
Hi @jpaitken 
You should look at some of the [examples](https://github.com/TwP/logging/tree/master/examples) with appenders and heirarchies..
But for a quick working example, check out [the gist i just put together](https://gist.github.com/ufo2mstar/a1ae076e4dba04aeab4e8b7a3c28a58b).
Cheers!
