### ISSUE TITLE
Proposal: Some restructuring around working examples

### ISSUE THREAD

**Issue by ufo2mstar** [TwP/logging#177]
Hey @TwP ,
The [examples](https://github.com/TwP/logging/tree/master/examples) here are pretty good, but I did have some trouble [finding some specifics](http://www.rubydoc.info/gems/logging/file/README.md) that I wanted to apply to my logger, like `additive`ity  for log level inheritance, `caller_tracing` for tracing level setup etc.. would you mind me restructuring some of the [examples](https://github.com/TwP/logging/tree/master/examples) that we have here?

**Comment by TwP** [comment]
Pull requests are always welcome.
