### ISSUE TITLE
clean up output.log

### ISSUE THREAD

**Issue by mm580486** [TwP/logging#180]
hi guys

i want to limit output.log file for example i want only saved last 50000 record and remove older record, i can do ? how ?

**Comment by TwP** [comment]
The [`RollingFile`](https://github.com/TwP/logging/blob/master/lib/logging/appenders/rolling_file.rb) appender is the closest thing I can offer you. Unfortunately it does not support limiting the file by the number of log records written. It can roll the file based on size and by age.
