### ISSUE TITLE
Log directory is not created

### ISSUE THREAD

**Issue by boonware** [TwP/logging#183]
If the configured log file is in a directory and the directory does not exist then the application fails. For example, if my log file is `log/service.log` and the directory `log` does not exist then I get the error message `log is not writable`. It would be better if this recovered and attempted to create the directory itself.

**Comment by TwP** [comment]
Setting up the filesystem for the application is outside the purview of the logging gem. Ownership and permissions for the log directory will need to be specified, and that is going to add complexity.
