### ISSUE TITLE
How to initialize logging and use it everyway with default configs?

### ISSUE THREAD

**Issue by omurbekjk** [TwP/logging#192]
How to configure logger with colors and outputs, and use it in another ruby classes.
Example, `logger` should log messages to the `console` and `development.log`.

**Comment by TwP** [comment]
Take a look at the [examples](https://github.com/TwP/logging/tree/master/examples) folder here in the repo. The [`examples/appenders.rb`](https://github.com/TwP/logging/blob/master/examples/appenders.rb) file demonstrates how to log to both stdout and a file. The [`examples/colorization.rb`](https://github.com/TwP/logging/blob/master/examples/colorization.rb) file demonstrates adding colorization to an appender via a layout.
