### ISSUE TITLE
Custom format of Layout#format_obj

### ISSUE THREAD

**Issue by jessebs** [TwP/logging#195]
I have a class that I'd like to pass instances of to the logger but don't want the class name displayed.  In Layout#format_obj, the only class that doesn't get the class name prepended to the message is String.  I'd like a way to turn off the class name prepending.

**Comment by TwP** [comment]
The default method used to format Ruby Objects is via the `to_s` method on each object. If you define this method for the objects you are logging, then you can control how they appear in the log messages.

Look into the `format_as` method provided by the Logging framework:
- https://github.com/TwP/logging/blob/master/examples/formatting.rb#L28-L30
- https://github.com/TwP/logging/blob/master/lib/logging.rb#L283

If you need anything more complex, then you will have to define your own `Layout` class to do what you want.
