### ISSUE TITLE
wrong number of arguments

### ISSUE THREAD

**Issue by UnConundrum** [TwP/logging#202]
New user with basic setup.   We have a class called Bill.  Within that class I have added:

`	require 'logging'`
`	attr_reader :log`
`	def initialize() @log = Logging.logger[self]; end`

When I do a Bill.new I get:
> ArgumentError: wrong number of arguments (given 1, expected 0)

We are using Rails 5.2.1 and Ruby 2.5.0p0
Appreciate any suggestions.

**Comment by TwP** [comment]
I'm afraid there is not enough information here for me to give you an intelligent suggestions. Do you have a complete stack trace you can share? That might contain some helpful information.
