### ISSUE TITLE
log_event overrides Kernel's `method` method

### ISSUE THREAD

**Issue by dorner** [TwP/logging#211]
When trying to debug methods using TracePoint, Logging causes a crash because it has an accessor called `method`. This override's Kernel's `method` definition, meaning it's impossible to get the method called and in fact crashes (since `method()` requires one parameter, not zero).

**Comment by TwP** [comment]
Could you please provide a link to where this `method` accessor is defined in the Logging codebase?

**Comment by TwP** [comment]
Nevermind - found it!

https://github.com/TwP/logging/blob/ae6cab195efa19f21b85f7bcb84e4ccf4084e3ba/lib/logging/log_event.rb#L18

Working on a fix now.

**Comment by dorner** [comment]
Thanks for the fix!
