### ISSUE TITLE
Custom timestamp format for JSON/YAML

### ISSUE THREAD

**Issue by tavlima** [TwP/logging#222]
It should be possible to customize the timestamp format used by both the yaml and json patterns. AFAICS, the only viable approach would be to change the `DIRECTIVE_TABLE` constant to use a custom function. And if you want to leverage the `apply_utc_offset`, that custom function would need to be monkey patched.

FWIW, I am aware the current formatting follows the ISO8601 standard, which is always good. What got me into this is the fact that some log consumers are not happy with the milliseconds part of the timestamp.

**Comment by TwP** [comment]
You can already specify the timestamp format using the `:date_pattern` option when creating the layout - https://github.com/TwP/logging/blob/master/examples/reusing_layouts.rb#L25-L28

The `:date_pattern` string is passed to the [`strftime`](https://apidock.com/ruby/DateTime/strftime) method, so the pattern should follow those formatting rules.
