### ISSUE TITLE
Conflict with mkmf

### ISSUE THREAD

**Issue by laleshii** [TwP/logging#242]
Your top level class name seems to be in direct conflict with the `mkmf` standard library.

```
require 'mkmf'
> Logging
=> MakeMakefile::Logging
```

Not sure what the best course of action is here. Might be worth considering changing it.

**Comment by TwP** [comment]
This is an error with `mkmf.rb` itself. According to the code comment [here](https://github.com/ruby/ruby/blob/master/lib/mkmf.rb#L297-L303), the `MakeMakefile::Logging` module should not be exposed at the top-level of the object space.

> This module and its associated methods are meant for internal use only.

I'd suggest taking this up with the core ruby team and let them know that their abstractions are leaking.
