### ISSUE TITLE
ability to limit backtrace size

### ISSUE THREAD

**Issue by rubycut** [TwP/logging#60]
I am running eventmachine programs, every time I receive log error on my emails, it's like over 200 lines long.

It would be nice if I couldn't limit backtrace size by sending integer as backtrace option, not only false and true.

**Comment by TwP** [comment]
This case can be handled by creating your own [layout](https://github.com/TwP/logging/blob/master/lib/logging/layout.rb) class and attaching the layout to the email appender. Your layout would be responsible for formatting backtrace lines appropriately.
