### ISSUE TITLE
Configurable format for DateRoller

### ISSUE THREAD

**Issue by jabalsad** [TwP/logging#77]
Hi,

Is there any chance you can add an option to make the format used for the filename in the DateRoller configurable?

**Comment by TwP** [comment]
I would love to make the date format configurable. :+1:

**Comment by TwP** [comment]
Look back through the commits, it appears that https://github.com/TwP/logging/commit/5a0092e3412c1f8642509d7019e4e87c5b91a9a6 has added this functionality. This will be included with the 2.0 release of the logging gem.

The specification is here: https://github.com/TwP/logging/blob/two-point-oh/lib/logging/appenders/rolling_file.rb#L64-67
