### ISSUE TITLE
Guidelines on how to add a custom appender

### ISSUE THREAD

**Issue by yourtallness** [TwP/logging#81]
Hello,

I am trying to write an appender to log to a set of Kafka brokers. I have created a file under /lib/appenders named kafka.rb and I am inheriting from ::Logging::Appender as per the examples of email / Syslog, etc included in the gem.

In order to load also my appender I am doing the following in a helper file:

Logging.module_eval do
  # Also load our custom appenders
  require_relative '../../lib/logging/appenders/kafka'
end

In particular controller where I wish to use this appender, I define a logger and add this appender to it.

Is there an easier way to make Logging aware of user defined appender?
Should I be adding it to the auto-loaded modules?

Thanks in advance

**Comment by sshaw** [comment]
> Is there an easier way to make Logging aware of user defined appender?

@yourtallness it appears the way to do this is to add a module method to `Logging::Appenders` that returns an instance of your custom logger. Then do the following:

```ruby
log_instance.add_appenders(Logging::Appenders.your_appender(options))
```

See [my Airbrake appender](https://github.com/sshaw/logging-appenders-airbrake) for more details.

**Comment by TwP** [comment]
I've updated the README with documentation on the preferred way to add an appender. Take a look at https://github.com/twp/logging-email for an example appender.
