### ISSUE TITLE
Non 'age' file based rotation

### ISSUE THREAD

**Issue by acetang** [TwP/logging#83]
Date roller should rotate based on system time instead of using a separate 'age' file. The most current log file should have the date format appended to it.

**Comment by TwP** [comment]
The `.age` file is there to keep track of when the file was last rolled. This allows the ruby program to be able to age off older log files even if the process is restarted. This is the closest I could get to a self-contained `logrotate` simulacrum via the logging gem.

Keeping track of system time via an internal variable is fine until the ruby process restarts. That datestamp needs to be persisted somewhere, and the filesystem is handily close by. The `.age` file is the least hackish of all the hacks I could think of at the time.

Immediately adding the datestamp to the log file is certainly an option. Again, I had `logrotate` in mind when I was writing this code.

**Comment by TwP** [comment]
Please do submit a pull request if you would like to see this feature implemented. For the time being I am going to close out this issue.
