### ISSUE TITLE
New appender

### ISSUE THREAD

**Issue by diegobernardes** [TwP/logging#84]
Hi,

There is any documentation that explains how to create a new appender?
I need a ZeroMQ appender.

Thanks.

**Comment by TwP** [comment]
Also take a look at the [`Syslog`](https://github.com/TwP/logging/blob/master/lib/logging/appenders/syslog.rb) appender for a relatively simple example of an appender. The syslog appender is self contained and mostly straightforward. The IO based appenders are a little harder to follow in that they inherit from a superclass and include the buffering module.
