### ISSUE TITLE
Problematic licensing

### ISSUE THREAD

**Issue by michaelkruglos** [TwP/logging#85]
Hi,
There's a file color_scheme.rb in the source of the gem.
This file is originally GPL, but the license of the gem is MIT.
This mixture taints the gem's license.
Please, consider removing or re-implementing this file.

**Comment by TwP** [comment]
Regarding the `color_scheme.rb` file, I chatted with Jeremy in person and he is cool with this file being present in the logging gem. @copiousfreetime, would you like to chime in here on this thread?

**Comment by copiousfreetime** [comment]
@jpmoral yes, I'm the original author of `color_scheme.rb` file in both highline and in logging. I am fine with the file being licensed under the same terms as the license for the gem it is included in. So for highline that is GPL v2 and for logging that is MIT. I'll make a pull request for logging that explicitly states that.

**Comment by jpmoral** [comment]
@TwP, @copiousfreetime thanks for looking into this!
