### ISSUE TITLE
Better understanding rolling file appender

### ISSUE THREAD

**Issue by jabalsad** [TwP/logging#88]
Hi,

I'd like to understand what's the necessity behind this line of code:
https://github.com/TwP/logging/blob/master/lib/logging/appenders/rolling_file.rb#L324

    files = Dir.glob(@glob).find_all {|fn| @rgxp =~ fn}

Specifically, I'm trying to understand why we need to check if the files match a regular expression after we already filtered them using a glob. 

The motivation for my question is that I'm trying to implement a RollingFile appender that is compatible with the current appender, but allows the consumer to specify their own datetime format. Of course, they might specify something that doesn't match the given regex in which case part of the code will break due to no longer finding old files to delete.

If the choice for adding this line is mostly paranoia, then I can consider adding an appender that doesn't perform this regex matching.

**Comment by TwP** [comment]
The `Dir.glob` method does not accept regular expressions for filtering files. So the glob pattern is used to pre-filter our list of files, and the regular expression is used to select just those files that match our datestamp pattern.

Thank you for looking into a custom date format rolling appender. If you are still working on that it would be a fantastic addition to the logging gem.

:+1:
